version: '3.8'

networks:
    hadoop-net:
        driver: bridge

services:

  namenode:
#    build: ./NameNode
    image: profesorbigdata/hadoop-namenode-image-profesor:v1.0
    container_name: namenode
    hostname: namenode
    command: /opt/bd/start-daemons.sh
    ports:
        - "9870:9870"
        - "8889:8889" #Jupyter Notebook
    volumes: 
      - ./notebooks:/media/notebooks #../notebooks Es el directorio local que es compartido con el contenedor
    networks:
        - hadoop-net

  resourcemanager:
#    build: ./ResourceManager
    image: profesorbigdata/hadoop-resourcemanager-image-profesor:v1.0
    container_name: resourcemanager
    hostname: resourcemanager
    command: /opt/bd/start-daemons.sh
    ports:
        - "8088:8088"
    networks:
        - hadoop-net

  dnnm:
#    build: ./DataNode-NodeManager
    image: profesorbigdata/hadoop-datanode-image-profesor:v1.0
    depends_on:
        - namenode
        - resourcemanager
    command: /opt/bd/start-daemons.sh
    networks:
        - hadoop-net


